var annotated_dup =
[
    [ "ColorDepth", "struct_color_depth.html", "struct_color_depth" ],
    [ "Colour", "class_colour.html", "class_colour" ],
    [ "DiskSampleDistributor", "class_disk_sample_distributor.html", "class_disk_sample_distributor" ],
    [ "FastSqrt", "struct_fast_sqrt.html", "struct_fast_sqrt" ],
    [ "Greatest", "struct_greatest.html", "struct_greatest" ],
    [ "ICamera", "class_i_camera.html", "class_i_camera" ],
    [ "IMaterial", "class_i_material.html", "class_i_material" ],
    [ "IRaycastable", "class_i_raycastable.html", "class_i_raycastable" ],
    [ "ISampleDistributor", "class_i_sample_distributor.html", "class_i_sample_distributor" ],
    [ "ISampleGenerator", "class_i_sample_generator.html", "class_i_sample_generator" ],
    [ "JitteredSampleGenerator", "class_jittered_sample_generator.html", "class_jittered_sample_generator" ],
    [ "LightIntensity", "class_light_intensity.html", "class_light_intensity" ],
    [ "Matrix4", "class_matrix4.html", "class_matrix4" ],
    [ "OrtagonalCamera", "class_ortagonal_camera.html", "class_ortagonal_camera" ],
    [ "PerspectiveCamera", "class_perspective_camera.html", "class_perspective_camera" ],
    [ "Plane", "class_plane.html", "class_plane" ],
    [ "RandomSampleGenerator", "class_random_sample_generator.html", "class_random_sample_generator" ],
    [ "Ray", "class_ray.html", "class_ray" ],
    [ "RayTracer", "class_ray_tracer.html", "class_ray_tracer" ],
    [ "RegularSampleGenerator", "class_regular_sample_generator.html", "class_regular_sample_generator" ],
    [ "RenderTarget", "class_render_target.html", "class_render_target" ],
    [ "Sampler", "class_sampler.html", "class_sampler" ],
    [ "Smallest", "struct_smallest.html", "struct_smallest" ],
    [ "Sphere", "class_sphere.html", "class_sphere" ],
    [ "SquareSampleDistributor", "class_square_sample_distributor.html", "class_square_sample_distributor" ],
    [ "ToRadians", "class_to_radians.html", null ],
    [ "Triangle", "class_triangle.html", "class_triangle" ],
    [ "Vector2", "class_vector2.html", "class_vector2" ],
    [ "Vector3", "class_vector3.html", "class_vector3" ],
    [ "Vector4", "class_vector4.html", "class_vector4" ],
    [ "Vertex2", "class_vertex2.html", "class_vertex2" ],
    [ "Vertex3", "class_vertex3.html", null ],
    [ "VertexProcessor", "class_vertex_processor.html", "class_vertex_processor" ]
];